const { ROLES, WORKSPACES } = require('./types');

const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.BNA_ADMIN, ROLES.OPERATOR, ROLES.SYSTEM];
const BNA_HELPER_ROLES = [...ADMIN_ROLES, ROLES.PARENT, ROLES.STUDENT];
const PROVIDER_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATOR, ROLES.PROVIDER_ADMIN, ROLES.PARTICIPANT, ROLES.SYSTEM];

function action(definition) {
  return {
    required_inputs: [],
    optional_inputs: [],
    validation: {},
    dry_run_supported: true,
    approval_required: false,
    related_routes: [],
    ui_button_labels: [],
    telegram_intent_examples: [],
    ...definition,
  };
}

const ACTIONS = [
  action({
    action_id: 'create_task',
    label: 'Create task',
    description: 'Create an internal Operations task from typed inputs or natural language.',
    category: 'tasks',
    page_contexts: ['tasks', 'dashboard', 'internal_dialogue', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['title'],
    optional_inputs: ['notes', 'stage', 'category', 'urgency', 'assigned_to', 'project', 'due_date'],
    validation: { title: 'non_empty_string' },
    execution_handler: 'tasks.create',
    audit_log_event: 'task_created',
    success_message: 'Task created.',
    failure_message: 'Task could not be created.',
    related_routes: ['/operations?view=tasks'],
    ui_button_labels: ['Create Task', 'Add Task', 'Save Task'],
    telegram_intent_examples: ['Create a task to call the parent tomorrow', 'File this as a task for Shloimie'],
  }),
  action({
    action_id: 'update_task_stage',
    label: 'Update task stage',
    description: 'Move a task to another Operations stage.',
    category: 'tasks',
    page_contexts: ['tasks', 'task_detail', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['task_id', 'stage'],
    optional_inputs: ['verification_notes'],
    validation: { task_id: 'number', stage: 'known_task_stage' },
    execution_handler: 'tasks.updateStage',
    audit_log_event: 'task_stage_updated',
    success_message: 'Task stage updated.',
    failure_message: 'Task stage could not be updated.',
    related_routes: ['/operations?view=tasks'],
    ui_button_labels: ['Move Task', 'Mark Done', 'Archive'],
    telegram_intent_examples: ['Move task 42 to done', 'Update task #17 to in progress'],
  }),
  action({
    action_id: 'add_timeline_note',
    label: 'Add timeline note',
    description: 'Add an internal note to an Operations timeline or dialogue thread.',
    category: 'communications',
    page_contexts: ['internal_dialogue', 'task_detail', 'student_detail', 'provider_detail'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['note'],
    optional_inputs: ['related_type', 'related_id', 'visibility'],
    validation: { note: 'non_empty_string' },
    execution_handler: 'timeline.addNote',
    audit_log_event: 'timeline_note_added',
    success_message: 'Timeline note added.',
    failure_message: 'Timeline note could not be added.',
    related_routes: ['/operations?view=internal_dialogue'],
    ui_button_labels: ['Add Note', 'Save Note'],
    telegram_intent_examples: ['Add a private note that the parent asked about billing'],
  }),

  action({
    action_id: 'find_latest_newsletter_draft',
    label: 'Find latest newsletter draft',
    description: 'Find the newest saved weekly newsletter draft.',
    category: 'newsletter',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['project', 'status'],
    execution_handler: 'content.findLatestNewsletterDraft',
    audit_log_event: 'newsletter_draft_found',
    success_message: 'Newsletter draft found.',
    failure_message: 'No newsletter draft was found.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Latest Newsletter', 'Open Draft'],
    telegram_intent_examples: ['Find the latest newsletter draft', 'Open the newsletter'],
  }),
  action({
    action_id: 'refine_newsletter_draft',
    label: 'Refine newsletter draft',
    description: 'Refine a saved newsletter draft and save a revision when a draft exists.',
    category: 'newsletter',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['output_id', 'draft_body', 'instruction', 'save_revision'],
    validation: { output_id: 'optional_number', draft_body: 'optional_string' },
    execution_handler: 'content.refineNewsletterDraft',
    audit_log_event: 'newsletter_draft_refined',
    success_message: 'Newsletter draft refined.',
    failure_message: 'Newsletter draft could not be refined.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Refine Newsletter', 'Save Revision'],
    telegram_intent_examples: ['Refine the newsletter', 'Polish the latest weekly update'],
  }),
  action({
    action_id: 'save_newsletter_revision',
    label: 'Save newsletter revision',
    description: 'Save a revised newsletter body as a new content output revision.',
    category: 'newsletter',
    page_contexts: ['content'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['source_output_id', 'title', 'job_id'],
    execution_handler: 'content.saveNewsletterRevision',
    audit_log_event: 'newsletter_revision_saved',
    success_message: 'Newsletter revision saved.',
    failure_message: 'Newsletter revision could not be saved.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Save Revision'],
    telegram_intent_examples: ['Save that newsletter revision'],
  }),
  action({
    action_id: 'approve_newsletter',
    label: 'Approve newsletter',
    description: 'Mark a newsletter draft approved after human review.',
    category: 'newsletter',
    page_contexts: ['content', 'communications'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['output_id'],
    approval_required: true,
    execution_handler: 'content.approveNewsletter',
    audit_log_event: 'newsletter_approved',
    success_message: 'Newsletter approved.',
    failure_message: 'Newsletter could not be approved.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Approve Newsletter'],
    telegram_intent_examples: ['Approve newsletter 12'],
  }),
  action({
    action_id: 'draft_email_from_newsletter',
    label: 'Draft email from newsletter',
    description: 'Create an email draft using an approved or draft newsletter body.',
    category: 'email',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['output_id', 'newsletter_body', 'audience', 'identity'],
    execution_handler: 'email.draftFromNewsletter',
    audit_log_event: 'email_draft_created',
    success_message: 'Email draft created.',
    failure_message: 'Email draft could not be created.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Draft Email', 'Email This'],
    telegram_intent_examples: ['Draft an email from the newsletter', 'Turn the newsletter into an email'],
  }),
  action({
    action_id: 'draft_email',
    label: 'Draft email',
    description: 'Create a safe email draft without sending it.',
    category: 'email',
    page_contexts: ['communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['subject', 'body', 'audience', 'identity', 'source_text'],
    execution_handler: 'email.draft',
    audit_log_event: 'email_draft_created',
    success_message: 'Email draft created.',
    failure_message: 'Email draft could not be created.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Draft Email', 'Create Email Draft'],
    telegram_intent_examples: ['Draft an email to parents about tomorrow', 'Write an email from Rabbi Sheller'],
  }),
  action({
    action_id: 'refine_email',
    label: 'Refine email',
    description: 'Refine an email draft without sending it.',
    category: 'email',
    page_contexts: ['communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['instruction', 'subject'],
    execution_handler: 'email.refine',
    audit_log_event: 'email_refined',
    success_message: 'Email refined.',
    failure_message: 'Email could not be refined.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Refine Email'],
    telegram_intent_examples: ['Tighten this email', 'Make this email warmer'],
  }),
  action({
    action_id: 'approve_email',
    label: 'Approve email',
    description: 'Approve an email draft for scheduling or sending.',
    category: 'email',
    page_contexts: ['communications'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['draft_id'],
    approval_required: true,
    execution_handler: 'email.approve',
    audit_log_event: 'email_approved',
    success_message: 'Email approved.',
    failure_message: 'Email could not be approved.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Approve Email'],
    telegram_intent_examples: ['Approve email draft 5'],
  }),
  action({
    action_id: 'schedule_email',
    label: 'Schedule email',
    description: 'Schedule an email only after approval and connector readiness.',
    category: 'email',
    page_contexts: ['communications'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['subject', 'body', 'scheduled_for'],
    optional_inputs: ['audience', 'identity'],
    approval_required: true,
    execution_handler: 'email.schedule',
    audit_log_event: 'email_schedule_requested',
    success_message: 'Email scheduled.',
    failure_message: 'Email could not be scheduled.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Schedule Email'],
    telegram_intent_examples: ['Schedule this email for Monday'],
  }),
  action({
    action_id: 'send_test_email',
    label: 'Send test email',
    description: 'Send a test email only when approved and email connector is configured.',
    category: 'email',
    page_contexts: ['communications', 'settings'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['to', 'subject', 'body'],
    approval_required: true,
    execution_handler: 'email.sendTest',
    audit_log_event: 'test_email_send_requested',
    success_message: 'Test email sent.',
    failure_message: 'Test email was not sent.',
    related_routes: ['/operations?view=settings&section=email'],
    ui_button_labels: ['Send Test Email'],
    telegram_intent_examples: ['Send a test email to me'],
  }),
  action({
    action_id: 'pause_scheduled_email',
    label: 'Pause scheduled email',
    description: 'Pause a scheduled email send.',
    category: 'email',
    page_contexts: ['communications'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['schedule_id'],
    approval_required: true,
    execution_handler: 'email.pauseScheduled',
    audit_log_event: 'scheduled_email_paused',
    success_message: 'Scheduled email paused.',
    failure_message: 'Scheduled email could not be paused.',
    ui_button_labels: ['Pause Email'],
    telegram_intent_examples: ['Pause scheduled email 8'],
  }),
  action({
    action_id: 'view_email_log',
    label: 'View email log',
    description: 'Read recent email log entries.',
    category: 'email',
    page_contexts: ['communications', 'settings'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['limit', 'status'],
    execution_handler: 'email.viewLog',
    audit_log_event: 'email_log_viewed',
    success_message: 'Email log loaded.',
    failure_message: 'Email log could not be loaded.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['View Email Log'],
    telegram_intent_examples: ['Show recent email log'],
  }),

  action({
    action_id: 'create_calendar_event',
    label: 'Create calendar event',
    description: 'Create an internal BNA calendar event without requiring Google Calendar.',
    category: 'calendar',
    page_contexts: ['calendar', 'student_portal', 'parent_portal', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['title', 'start_at'],
    optional_inputs: ['end_at', 'description', 'visibility', 'source', 'related_type', 'related_id', 'meeting_url'],
    validation: { title: 'non_empty_string', start_at: 'datetime' },
    execution_handler: 'calendar.createEvent',
    audit_log_event: 'calendar_event_created',
    success_message: 'Calendar event created.',
    failure_message: 'Calendar event could not be created.',
    related_routes: ['/operations?view=calendar'],
    ui_button_labels: ['New Event', 'Create Event'],
    telegram_intent_examples: ['Create a calendar event for parent meeting on 2026-06-18 16:00'],
  }),
  action({
    action_id: 'update_calendar_event',
    label: 'Update calendar event',
    description: 'Update an internal calendar event.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['event_id'],
    optional_inputs: ['title', 'start_at', 'end_at', 'description', 'visibility', 'status'],
    execution_handler: 'calendar.updateEvent',
    audit_log_event: 'calendar_event_updated',
    success_message: 'Calendar event updated.',
    failure_message: 'Calendar event could not be updated.',
    related_routes: ['/operations?view=calendar'],
    ui_button_labels: ['Edit Event'],
    telegram_intent_examples: ['Move calendar event 12 to Thursday'],
  }),
  action({
    action_id: 'delete_calendar_event',
    label: 'Archive calendar event',
    description: 'Archive an internal calendar event. Destructive external deletes require approval.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['event_id'],
    approval_required: true,
    execution_handler: 'calendar.archiveEvent',
    audit_log_event: 'calendar_event_archived',
    success_message: 'Calendar event archived.',
    failure_message: 'Calendar event could not be archived.',
    related_routes: ['/operations?view=calendar'],
    ui_button_labels: ['Archive Event', 'Delete Event'],
    telegram_intent_examples: ['Delete calendar event 12'],
  }),
  action({
    action_id: 'create_student_schedule_item',
    label: 'Create student schedule item',
    description: 'Create a student-visible schedule item in the BNA calendar.',
    category: 'student',
    page_contexts: ['student_detail', 'student_portal', 'calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['title', 'start_at'],
    optional_inputs: ['student_id', 'assignment_id', 'description'],
    execution_handler: 'calendar.createStudentScheduleItem',
    audit_log_event: 'student_schedule_item_created',
    success_message: 'Student schedule item created.',
    failure_message: 'Student schedule item could not be created.',
    related_routes: ['/student', '/operations?view=calendar'],
    ui_button_labels: ['Add Student Event'],
    telegram_intent_examples: ['Create a student-visible schedule item for Meir tomorrow'],
  }),
  action({
    action_id: 'create_parent_visible_event',
    label: 'Create parent-visible event',
    description: 'Create a parent-visible child calendar item.',
    category: 'parent',
    page_contexts: ['parent_portal', 'student_detail', 'calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['title', 'start_at'],
    optional_inputs: ['student_id', 'description'],
    execution_handler: 'calendar.createParentVisibleEvent',
    audit_log_event: 'parent_visible_event_created',
    success_message: 'Parent-visible event created.',
    failure_message: 'Parent-visible event could not be created.',
    related_routes: ['/parent', '/operations?view=calendar'],
    ui_button_labels: ['Add Parent Event'],
    telegram_intent_examples: ['Create a parent-visible event for the trip deadline'],
  }),
  action({
    action_id: 'create_provider_class_session',
    label: 'Create provider class session',
    description: 'Create a provider program session without exposing BNA school accountability.',
    category: 'provider',
    page_contexts: ['provider_workspace', 'provider_participant', 'calendar'],
    allowed_roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATOR, ROLES.PROVIDER_ADMIN, ROLES.SYSTEM],
    allowed_workspaces: [WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['title', 'start_at'],
    optional_inputs: ['description', 'meeting_url'],
    execution_handler: 'calendar.createProviderClassSession',
    audit_log_event: 'provider_class_session_created',
    success_message: 'Provider class session created.',
    failure_message: 'Provider class session could not be created.',
    related_routes: ['/provider-participant', '/operations?workspace=rabbi_sheller_provider&view=calendar'],
    ui_button_labels: ['New Class Session'],
    telegram_intent_examples: ['Create Rabbi Sheller class session on Sunday at 7'],
  }),
  action({
    action_id: 'sync_google_calendar',
    label: 'Sync Google Calendar',
    description: 'Run Google Calendar sync only after explicit approval and connector readiness.',
    category: 'calendar',
    page_contexts: ['settings', 'calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA],
    approval_required: true,
    execution_handler: 'calendar.syncGoogleCalendar',
    audit_log_event: 'google_calendar_sync_requested',
    success_message: 'Google Calendar sync requested.',
    failure_message: 'Google Calendar sync could not run.',
    ui_button_labels: ['Sync Google Calendar'],
    telegram_intent_examples: ['Sync Google Calendar'],
  }),
  action({
    action_id: 'sync_google_classroom',
    label: 'Sync Google Classroom',
    description: 'Run Google Classroom sync only after explicit approval and connector readiness.',
    category: 'calendar',
    page_contexts: ['settings', 'assignments'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA],
    approval_required: true,
    execution_handler: 'calendar.syncGoogleClassroom',
    audit_log_event: 'google_classroom_sync_requested',
    success_message: 'Google Classroom sync requested.',
    failure_message: 'Google Classroom sync could not run.',
    ui_button_labels: ['Sync Google Classroom'],
    telegram_intent_examples: ['Sync Google Classroom'],
  }),
  action({
    action_id: 'open_calendar_event',
    label: 'Open calendar event',
    description: 'Return a direct route to a calendar event detail.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: [...ADMIN_ROLES, ROLES.PARENT, ROLES.STUDENT, ROLES.PROVIDER_ADMIN, ROLES.PARTICIPANT],
    allowed_workspaces: [WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['event_id'],
    execution_handler: 'calendar.openEvent',
    audit_log_event: 'calendar_event_opened',
    success_message: 'Calendar event route opened.',
    failure_message: 'Calendar event route could not be opened.',
    related_routes: ['/operations?view=calendar', '/parent', '/student', '/provider-participant'],
    ui_button_labels: ['Open Event'],
    telegram_intent_examples: ['Open calendar event 12'],
  }),
  action({
    action_id: 'mark_event_parent_visible',
    label: 'Mark event parent-visible',
    description: 'Make an event visible to parents after admin review.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['event_id'],
    approval_required: true,
    execution_handler: 'calendar.markParentVisible',
    audit_log_event: 'calendar_event_marked_parent_visible',
    success_message: 'Event marked parent-visible.',
    failure_message: 'Event visibility could not be changed.',
    ui_button_labels: ['Parent Visible'],
    telegram_intent_examples: ['Mark event 12 parent visible'],
  }),
  action({
    action_id: 'mark_event_student_visible',
    label: 'Mark event student-visible',
    description: 'Make an event visible to the assigned student after admin review.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['event_id'],
    approval_required: true,
    execution_handler: 'calendar.markStudentVisible',
    audit_log_event: 'calendar_event_marked_student_visible',
    success_message: 'Event marked student-visible.',
    failure_message: 'Event visibility could not be changed.',
    ui_button_labels: ['Student Visible'],
    telegram_intent_examples: ['Mark event 12 student visible'],
  }),
  action({
    action_id: 'mark_event_admin_only',
    label: 'Mark event admin-only',
    description: 'Restrict an event to internal/admin visibility.',
    category: 'calendar',
    page_contexts: ['calendar'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['event_id'],
    execution_handler: 'calendar.markAdminOnly',
    audit_log_event: 'calendar_event_marked_admin_only',
    success_message: 'Event marked admin-only.',
    failure_message: 'Event visibility could not be changed.',
    ui_button_labels: ['Admin Only'],
    telegram_intent_examples: ['Mark event 12 admin only'],
  }),

  action({
    action_id: 'generate_whatsapp_from_newsletter',
    label: 'Generate WhatsApp from newsletter',
    description: 'Generate a WhatsApp draft from a newsletter without sending it.',
    category: 'whatsapp',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['newsletter_body', 'output_id', 'audience'],
    execution_handler: 'whatsapp.draftFromNewsletter',
    audit_log_event: 'whatsapp_draft_created',
    success_message: 'WhatsApp draft created.',
    failure_message: 'WhatsApp draft could not be created.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Draft WhatsApp'],
    telegram_intent_examples: ['Make a WhatsApp update from the newsletter'],
  }),
  action({
    action_id: 'draft_whatsapp_message',
    label: 'Draft WhatsApp message',
    description: 'Create a WhatsApp draft for BNA or provider communications without sending it.',
    category: 'whatsapp',
    page_contexts: ['communications', 'content', 'parent_detail', 'provider_workspace', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['body', 'message', 'source_text', 'audience', 'to', 'phone', 'workspace_key'],
    execution_handler: 'whatsapp.draft',
    audit_log_event: 'whatsapp_draft_created',
    success_message: 'WhatsApp draft created.',
    failure_message: 'WhatsApp draft could not be created.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Draft WhatsApp', 'Create WhatsApp Draft'],
    telegram_intent_examples: ['Draft a WhatsApp update for parents', 'Write a WhatsApp to Rabbi Sheller members'],
  }),
  action({
    action_id: 'generate_whatsapp_link',
    label: 'Generate WhatsApp link',
    description: 'Create a prefilled wa.me link without using the WhatsApp API.',
    category: 'whatsapp',
    page_contexts: ['communications', 'contacts', 'settings', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['to', 'phone', 'audience'],
    execution_handler: 'whatsapp.generateLink',
    audit_log_event: 'whatsapp_link_generated',
    success_message: 'WhatsApp link generated.',
    failure_message: 'WhatsApp link could not be generated.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['Generate WhatsApp Link', 'Open WhatsApp'],
    telegram_intent_examples: ['Make a WhatsApp link for this message'],
  }),
  action({
    action_id: 'send_whatsapp_via_wapi',
    label: 'Send WhatsApp via WAPI',
    description: 'Send an approved WhatsApp message through the WAPI connector.',
    category: 'whatsapp',
    page_contexts: ['communications', 'contacts', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['to', 'phone', 'signup_id', 'lead_id', 'student_id', 'typing_time'],
    approval_required: true,
    execution_handler: 'whatsapp.sendViaWapi',
    audit_log_event: 'whatsapp_send_requested',
    success_message: 'WhatsApp send executed.',
    failure_message: 'WhatsApp was not sent.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['Send WhatsApp', 'Send via WAPI'],
    telegram_intent_examples: ['Send this WhatsApp after approval', 'Send WhatsApp to lead 12'],
  }),
  action({
    action_id: 'send_whatsapp_to_group',
    label: 'Send WhatsApp to group',
    description: 'Prepare an approved WhatsApp group/broadcast send through the connector.',
    category: 'whatsapp',
    page_contexts: ['communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body', 'audience'],
    optional_inputs: ['group_id', 'workspace_key'],
    approval_required: true,
    execution_handler: 'whatsapp.sendGroup',
    audit_log_event: 'whatsapp_group_send_requested',
    success_message: 'WhatsApp group send requested.',
    failure_message: 'WhatsApp group send was not executed.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['Send Group WhatsApp'],
    telegram_intent_examples: ['Send this WhatsApp to the parent group after I approve'],
  }),
  action({
    action_id: 'send_parent_login_whatsapp',
    label: 'Draft parent login WhatsApp',
    description: 'Prepare the parent portal login WhatsApp copy; live send remains approval-gated.',
    category: 'whatsapp',
    page_contexts: ['contacts', 'parent_detail', 'parent_portal', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['parent_email', 'parent_name', 'student_id', 'url', 'phone'],
    approval_required: true,
    execution_handler: 'whatsapp.draftParentLogin',
    audit_log_event: 'parent_login_whatsapp_requested',
    success_message: 'Parent login WhatsApp prepared.',
    failure_message: 'Parent login WhatsApp could not be prepared.',
    related_routes: ['/operations?view=contacts', '/parent'],
    ui_button_labels: ['WhatsApp Login Link'],
    telegram_intent_examples: ['Send the parent login WhatsApp to this family'],
  }),
  action({
    action_id: 'send_weekly_update_whatsapp',
    label: 'Send weekly update WhatsApp',
    description: 'Prepare or send an approved parent weekly update by WhatsApp.',
    category: 'whatsapp',
    page_contexts: ['parent_detail', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['body'],
    optional_inputs: ['student_id', 'parent_email', 'phone', 'to'],
    approval_required: true,
    execution_handler: 'whatsapp.sendViaWapi',
    audit_log_event: 'weekly_update_whatsapp_requested',
    success_message: 'Weekly update WhatsApp requested.',
    failure_message: 'Weekly update WhatsApp was not sent.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['Send Weekly Update'],
    telegram_intent_examples: ['Send this weekly update by WhatsApp after approval'],
  }),
  action({
    action_id: 'log_whatsapp_message',
    label: 'Log WhatsApp message',
    description: 'Record a WhatsApp communication in the contact timeline without sending anything.',
    category: 'communications',
    page_contexts: ['communications', 'contacts', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['summary', 'direction', 'lead_id', 'signup_id', 'student_id', 'contact_type', 'follow_up_required'],
    execution_handler: 'whatsapp.logMessage',
    audit_log_event: 'whatsapp_message_logged',
    success_message: 'WhatsApp message logged.',
    failure_message: 'WhatsApp message could not be logged.',
    related_routes: ['/operations?view=communications'],
    ui_button_labels: ['Log WhatsApp', 'Add Timeline Note'],
    telegram_intent_examples: ['Log that I WhatsApped this parent'],
  }),
  action({
    action_id: 'view_whatsapp_thread',
    label: 'View WhatsApp thread',
    description: 'Load recent WhatsApp timeline entries for a contact or student.',
    category: 'communications',
    page_contexts: ['communications', 'contacts', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['lead_id', 'signup_id', 'student_id', 'limit'],
    execution_handler: 'whatsapp.viewThread',
    audit_log_event: 'whatsapp_thread_viewed',
    success_message: 'WhatsApp thread loaded.',
    failure_message: 'WhatsApp thread could not be loaded.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['View WhatsApp Thread'],
    telegram_intent_examples: ['Show WhatsApp history for this parent'],
  }),
  action({
    action_id: 'generate_weekly_update',
    label: 'Generate weekly parent update',
    description: 'Generate a parent-visible weekly update draft from permitted student context.',
    category: 'parent',
    page_contexts: ['parent_detail', 'student_detail', 'content', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id', 'student_name', 'learning', 'questions', 'links', 'source_text', 'from_latest_media', 'media_id', 'video_url', 'attendance_snapshot', 'payment_form_alerts'],
    execution_handler: 'parent.generateWeeklyUpdate',
    audit_log_event: 'weekly_update_generated',
    success_message: 'Weekly update draft created.',
    failure_message: 'Weekly update draft could not be created.',
    related_routes: ['/operations?view=students', '/parent'],
    ui_button_labels: ['Generate Weekly Update', 'Parent Update'],
    telegram_intent_examples: ['Generate this week’s parent update for Meir'],
  }),
  action({
    action_id: 'find_latest_uploaded_media',
    label: 'Find latest uploaded media',
    description: 'Find the newest uploaded video/audio/media record available for weekly update drafting.',
    category: 'content',
    page_contexts: ['content', 'telegram', 'ui_bot'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['media_id', 'content_job_id', 'source_type'],
    execution_handler: 'content.findLatestUploadedMedia',
    audit_log_event: 'latest_media_found',
    success_message: 'Latest media lookup completed.',
    failure_message: 'Latest media could not be found.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Find Latest Media'],
    telegram_intent_examples: ['Find the latest uploaded video/audio'],
  }),
  action({
    action_id: 'transcribe_or_parse_media_if_needed',
    label: 'Check media transcript/parse readiness',
    description: 'Check whether the latest uploaded media needs transcription or parsing before parent-ready drafting.',
    category: 'content',
    page_contexts: ['content', 'telegram', 'ui_bot'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['media_id', 'content_job_id'],
    execution_handler: 'content.transcribeOrParseMediaIfNeeded',
    audit_log_event: 'media_transcription_parse_checked',
    success_message: 'Media transcription/parse readiness checked.',
    failure_message: 'Media transcription/parse readiness could not be checked.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Check Transcript'],
    telegram_intent_examples: ['Transcribe or parse the latest uploaded media if needed'],
  }),
  action({
    action_id: 'summarize_weekly_topics',
    label: 'Summarize weekly topics',
    description: 'Summarize weekly topics from permitted source text or media transcript.',
    category: 'content',
    page_contexts: ['content', 'telegram', 'ui_bot'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['source_text', 'transcript_text', 'topics'],
    execution_handler: 'content.summarizeWeeklyTopics',
    audit_log_event: 'weekly_topics_summarized',
    success_message: 'Weekly topics summarized.',
    failure_message: 'Weekly topics could not be summarized.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Summarize Topics'],
    telegram_intent_examples: ['Summarize the topics we discussed this week'],
  }),
  action({
    action_id: 'extract_student_questions',
    label: 'Extract student questions',
    description: 'Extract parent-visible student questions from permitted source text or media transcript.',
    category: 'content',
    page_contexts: ['content', 'telegram', 'ui_bot'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['source_text', 'transcript_text', 'questions'],
    execution_handler: 'content.extractStudentQuestions',
    audit_log_event: 'student_questions_extracted',
    success_message: 'Student questions extracted.',
    failure_message: 'Student questions could not be extracted.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Extract Questions'],
    telegram_intent_examples: ['Extract the boys questions from this week'],
  }),
  action({
    action_id: 'generate_parent_newsletter',
    label: 'Generate parent newsletter',
    description: 'Generate a parent-ready newsletter draft from the weekly update context without sending email.',
    category: 'newsletter',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id', 'student_name', 'source_text', 'from_latest_media', 'media_id', 'newsletter_title'],
    execution_handler: 'parent.generateNewsletter',
    audit_log_event: 'parent_newsletter_generated',
    success_message: 'Parent newsletter draft created.',
    failure_message: 'Parent newsletter draft could not be created.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Generate Newsletter'],
    telegram_intent_examples: ['Make a newsletter from this week parent update'],
  }),
  action({
    action_id: 'generate_whatsapp_weekly_post',
    label: 'Generate weekly WhatsApp post',
    description: 'Generate a concise WhatsApp parent-group draft from the weekly update context without sending it.',
    category: 'whatsapp',
    page_contexts: ['content', 'communications', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id', 'student_name', 'source_text', 'from_latest_media', 'media_id', 'audience'],
    execution_handler: 'whatsapp.generateWeeklyPost',
    audit_log_event: 'weekly_whatsapp_post_generated',
    success_message: 'Weekly WhatsApp draft created.',
    failure_message: 'Weekly WhatsApp draft could not be created.',
    related_routes: ['/operations?view=communications&section=whatsapp'],
    ui_button_labels: ['Generate Weekly WhatsApp'],
    telegram_intent_examples: ['Make a WhatsApp post from the latest weekly update'],
  }),
  action({
    action_id: 'attach_video_to_parent_portal',
    label: 'Attach video to parent portal',
    description: 'Prepare a parent-visible video/image attachment for the weekly update after approval.',
    category: 'parent',
    page_contexts: ['content', 'parent_detail', 'student_detail'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id', 'video_url', 'media_url', 'drive_url', 'thumbnail_url', 'parent_visible'],
    approval_required: true,
    execution_handler: 'parent.attachVideoToPortal',
    audit_log_event: 'parent_portal_video_attachment_requested',
    success_message: 'Parent portal video attachment prepared.',
    failure_message: 'Parent portal video attachment could not be prepared.',
    related_routes: ['/operations?view=content', '/parent'],
    ui_button_labels: ['Attach Video'],
    telegram_intent_examples: ['Attach the latest video to the parent portal update'],
  }),
  action({
    action_id: 'save_weekly_update_revision',
    label: 'Save weekly update revision',
    description: 'Save a revised weekly parent update draft with parent-portal metadata.',
    category: 'parent',
    page_contexts: ['content', 'parent_detail', 'student_detail'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['body'],
    optional_inputs: ['job_id', 'content_job_id', 'title', 'student_id', 'links', 'parent_visible'],
    execution_handler: 'parent.saveWeeklyUpdateRevision',
    audit_log_event: 'weekly_update_revision_saved',
    success_message: 'Weekly update revision saved.',
    failure_message: 'Weekly update revision could not be saved.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Save Weekly Update Revision'],
    telegram_intent_examples: ['Save this weekly update revision'],
  }),
  action({
    action_id: 'publish_weekly_update_to_parent_portal',
    label: 'Publish weekly update to parent portal',
    description: 'Mark an approved weekly update as parent-visible.',
    category: 'parent',
    page_contexts: ['parent_detail', 'student_detail', 'content'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['body'],
    optional_inputs: ['student_id', 'student_name', 'links'],
    approval_required: true,
    execution_handler: 'parent.publishWeeklyUpdate',
    audit_log_event: 'weekly_update_published',
    success_message: 'Weekly update published to parent portal.',
    failure_message: 'Weekly update could not be published.',
    related_routes: ['/parent', '/operations?view=students'],
    ui_button_labels: ['Publish to Parent Portal'],
    telegram_intent_examples: ['Publish this weekly update to the parent portal'],
  }),
  action({
    action_id: 'prepare_rabbi_sheller_access_request',
    label: 'Prepare Rabbi Sheller access request',
    description: 'Prepare a safe checklist/message for access to Rabbi Sheller’s external class/member system.',
    category: 'provider',
    page_contexts: ['provider_workspace', 'settings', 'telegram'],
    allowed_roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATOR, ROLES.SYSTEM],
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['recipient', 'notes'],
    execution_handler: 'provider.prepareAccessRequest',
    audit_log_event: 'provider_access_request_prepared',
    success_message: 'Access request prepared.',
    failure_message: 'Access request could not be prepared.',
    related_routes: ['/operations?workspace=rabbi_sheller_provider&view=settings'],
    ui_button_labels: ['Prepare Access Request'],
    telegram_intent_examples: ['Prepare the Rabbi Sheller app access checklist'],
  }),
  action({
    action_id: 'create_report_problem_ticket',
    label: 'Report a problem',
    description: 'Create a support-ticket preview from the current UI context.',
    category: 'admin',
    page_contexts: ['operations_shell', 'settings', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['description'],
    optional_inputs: ['title', 'severity', 'category', 'page_context', 'screenshot_path', 'selector', 'bounding_box', 'route', 'note', 'reporter_user_id', 'reporter_role', 'workspace_id', 'status', 'assigned_to', 'created_task_id'],
    execution_handler: 'support.reportProblem',
    audit_log_event: 'problem_ticket_reported',
    success_message: 'Problem report prepared.',
    failure_message: 'Problem report could not be prepared.',
    related_routes: ['/operations?view=admin&section=tickets'],
    ui_button_labels: ['Report Problem', 'Send Bug Report'],
    telegram_intent_examples: ['Report a problem with this page'],
  }),
  action({
    action_id: 'summarize_current_page',
    label: 'Summarize current page',
    description: 'Summarize the current Operations page for the Super Admin assistant without exposing prompts.',
    category: 'bot',
    page_contexts: ['operations_shell', 'ui_bot'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['route', 'title', 'visible_counts'],
    execution_handler: 'assistant.summarizePage',
    audit_log_event: 'current_page_summarized',
    success_message: 'Page summary created.',
    failure_message: 'Page summary could not be created.',
    related_routes: ['/operations'],
    ui_button_labels: ['Summarize Page'],
    telegram_intent_examples: ['Summarize what I am looking at'],
  }),
  action({
    action_id: 'generate_social_posts_from_newsletter',
    label: 'Generate social posts from newsletter',
    description: 'Generate social copy drafts without publishing.',
    category: 'social',
    page_contexts: ['content', 'communications'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    optional_inputs: ['newsletter_body', 'output_id', 'channels'],
    execution_handler: 'social.draftFromNewsletter',
    audit_log_event: 'social_drafts_created',
    success_message: 'Social drafts created.',
    failure_message: 'Social drafts could not be created.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Make Social Posts'],
    telegram_intent_examples: ['Make social posts from the newsletter'],
  }),
  action({
    action_id: 'open_content_item_url',
    label: 'Open content item',
    description: 'Return a URL to a content item.',
    category: 'content',
    page_contexts: ['content'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['content_id'],
    execution_handler: 'content.openItemUrl',
    audit_log_event: 'content_item_opened',
    success_message: 'Content item route opened.',
    failure_message: 'Content item route could not be opened.',
    related_routes: ['/operations?view=content'],
    ui_button_labels: ['Open in UI'],
    telegram_intent_examples: ['Open content item 15'],
  }),

  action({
    action_id: 'show_today_plan',
    label: 'Show today plan',
    description: 'Show a student-safe today plan.',
    category: 'student',
    page_contexts: ['student_portal', 'student_helper'],
    allowed_roles: [ROLES.STUDENT, ROLES.BNA_ADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.SYSTEM],
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id'],
    execution_handler: 'student.showTodayPlan',
    audit_log_event: 'student_today_plan_shown',
    success_message: 'Today plan loaded.',
    failure_message: 'Today plan could not be loaded.',
    related_routes: ['/student'],
    ui_button_labels: ['Today Plan', 'Ask BNA Helper'],
    telegram_intent_examples: ['What do I need to do today?'],
  }),
  action({
    action_id: 'show_assignments',
    label: 'Show assignments',
    description: 'Show student-visible assignments only.',
    category: 'student',
    page_contexts: ['student_portal', 'parent_portal'],
    allowed_roles: BNA_HELPER_ROLES,
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id'],
    execution_handler: 'student.showAssignments',
    audit_log_event: 'student_assignments_shown',
    success_message: 'Assignments loaded.',
    failure_message: 'Assignments could not be loaded.',
    related_routes: ['/student', '/parent'],
    ui_button_labels: ['Assignments'],
    telegram_intent_examples: ['Show assignments'],
  }),
  action({
    action_id: 'explain_assignment',
    label: 'Explain assignment',
    description: 'Explain a student-visible assignment without admin-only notes.',
    category: 'student',
    page_contexts: ['student_portal', 'student_helper'],
    allowed_roles: [ROLES.STUDENT, ROLES.BNA_ADMIN, ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.SYSTEM],
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['assignment_id'],
    execution_handler: 'student.explainAssignment',
    audit_log_event: 'assignment_explained',
    success_message: 'Assignment explanation loaded.',
    failure_message: 'Assignment explanation could not be loaded.',
    related_routes: ['/student'],
    ui_button_labels: ['Explain'],
    telegram_intent_examples: ['Explain assignment 7'],
  }),
  action({
    action_id: 'create_help_request',
    label: 'Create help request',
    description: 'Create a parent/student-safe help request for staff.',
    category: 'communications',
    page_contexts: ['student_helper', 'parent_helper', 'messages_help'],
    allowed_roles: [ROLES.PARENT, ROLES.STUDENT, ...ADMIN_ROLES],
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['message'],
    execution_handler: 'support.createHelpRequest',
    audit_log_event: 'help_request_created',
    success_message: 'Help request created.',
    failure_message: 'Help request could not be created.',
    related_routes: ['/parent', '/student', '/operations?view=communications'],
    ui_button_labels: ['Ask for help', 'Ask BNA Helper', 'Parent Help'],
    telegram_intent_examples: ['Ask for help with my login'],
  }),
  action({
    action_id: 'show_child_calendar',
    label: 'Show child calendar',
    description: 'Show parent-visible child calendar events only.',
    category: 'parent',
    page_contexts: ['parent_portal', 'parent_helper'],
    allowed_roles: [ROLES.PARENT, ...ADMIN_ROLES],
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id'],
    execution_handler: 'parent.showChildCalendar',
    audit_log_event: 'parent_child_calendar_shown',
    success_message: 'Child calendar loaded.',
    failure_message: 'Child calendar could not be loaded.',
    related_routes: ['/parent'],
    ui_button_labels: ['Calendar', 'Show Calendar'],
    telegram_intent_examples: ['Show my child calendar'],
  }),
  action({
    action_id: 'draft_message_to_admin',
    label: 'Draft message to admin',
    description: 'Draft a parent-visible message to staff without exposing private internals.',
    category: 'parent',
    page_contexts: ['parent_helper', 'messages_help'],
    allowed_roles: [ROLES.PARENT, ...ADMIN_ROLES],
    allowed_workspaces: [WORKSPACES.BNA],
    required_inputs: ['message'],
    execution_handler: 'parent.draftMessageToAdmin',
    audit_log_event: 'parent_admin_message_drafted',
    success_message: 'Message draft created.',
    failure_message: 'Message draft could not be created.',
    related_routes: ['/parent'],
    ui_button_labels: ['Draft Message'],
    telegram_intent_examples: ['Draft a message to admin about pickup'],
  }),
  action({
    action_id: 'view_parent_visible_notes',
    label: 'View parent-visible notes',
    description: 'Read only notes explicitly marked parent-visible.',
    category: 'parent',
    page_contexts: ['parent_portal', 'parent_helper'],
    allowed_roles: [ROLES.PARENT, ...ADMIN_ROLES],
    allowed_workspaces: [WORKSPACES.BNA],
    optional_inputs: ['student_id'],
    execution_handler: 'parent.viewVisibleNotes',
    audit_log_event: 'parent_visible_notes_viewed',
    success_message: 'Parent-visible notes loaded.',
    failure_message: 'Parent-visible notes could not be loaded.',
    related_routes: ['/parent'],
    ui_button_labels: ['Visible Notes'],
    telegram_intent_examples: ['Show parent-visible notes'],
  }),

  action({
    action_id: 'create_provider_question_post',
    label: 'Create provider question/post',
    description: 'Create a structured provider participant question or post.',
    category: 'provider',
    page_contexts: ['provider_participant', 'provider_workspace'],
    allowed_roles: PROVIDER_ROLES,
    allowed_workspaces: [WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['body'],
    optional_inputs: ['visibility'],
    execution_handler: 'provider.createQuestionPost',
    audit_log_event: 'provider_question_post_created',
    success_message: 'Provider question/post created.',
    failure_message: 'Provider question/post could not be created.',
    related_routes: ['/provider-participant'],
    ui_button_labels: ['Post Question', 'Save Post'],
    telegram_intent_examples: ['Post this question for Rabbi Sheller'],
  }),
  action({
    action_id: 'update_provider_profile',
    label: 'Update provider profile',
    description: 'Update provider program/profile draft data.',
    category: 'provider',
    page_contexts: ['provider_workspace', 'provider_index'],
    allowed_roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.OPERATOR, ROLES.PROVIDER_ADMIN, ROLES.SYSTEM],
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['provider_id'],
    optional_inputs: ['display_name', 'summary', 'status'],
    approval_required: true,
    execution_handler: 'provider.updateProfile',
    audit_log_event: 'provider_profile_update_requested',
    success_message: 'Provider profile update saved.',
    failure_message: 'Provider profile could not be updated.',
    related_routes: ['/operations?view=service_providers'],
    ui_button_labels: ['Save Provider', 'Publish Provider'],
    telegram_intent_examples: ['Update Rabbi Sheller provider profile'],
  }),
  action({
    action_id: 'move_lead_stage',
    label: 'Move lead stage',
    description: 'Move a lead or pipeline card to a typed stage such as Payment Pending.',
    category: 'communications',
    page_contexts: ['contacts', 'pipelines', 'telegram'],
    allowed_roles: ADMIN_ROLES,
    allowed_workspaces: [WORKSPACES.PLATFORM, WORKSPACES.BNA, WORKSPACES.RABBI_SHELLER_PROVIDER],
    required_inputs: ['stage'],
    optional_inputs: ['lead_id', 'lead_name', 'pipeline'],
    execution_handler: 'crm.moveLeadStage',
    audit_log_event: 'lead_stage_update_requested',
    success_message: 'Lead stage update prepared.',
    failure_message: 'Lead stage could not be updated.',
    related_routes: ['/operations?view=pipelines', '/operations?view=contacts'],
    ui_button_labels: ['Move Lead', 'Payment Pending'],
    telegram_intent_examples: ['Move this lead to Payment Pending'],
  }),
];

const ACTIONS_BY_ID = new Map(ACTIONS.map((item) => [item.action_id, item]));

function listActions() {
  return ACTIONS.map((item) => ({ ...item }));
}

function getAction(actionId) {
  return ACTIONS_BY_ID.get(String(actionId || '').trim()) || null;
}

function actionIds() {
  return ACTIONS.map((item) => item.action_id);
}

module.exports = {
  ACTIONS,
  actionIds,
  getAction,
  listActions,
};
