const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');

const server = fs.readFileSync('server.js', 'utf8');
const googleIntegrations = fs.readFileSync('src/lib/bna/google-integrations.js', 'utf8');
const operations = fs.readFileSync('public/operations.html', 'utf8');
const student = fs.readFileSync('public/student.html', 'utf8');
const parent = fs.readFileSync('public/parent.html', 'utf8');
const envExample = fs.readFileSync('.env.example', 'utf8');

test('assignment schema, prompts, and API routes are bootstrapped', () => {
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_assignment_prompts/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_assignments/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_assignment_students/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_assignment_regenerations/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_video_processing_jobs/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_schedule_items/);
  assert.match(server, /original_prompt_text TEXT/);
  assert.match(server, /final_resolved_prompt TEXT/);
  assert.match(server, /generated_worksheet TEXT/);
  assert.match(server, /edited_worksheet TEXT/);
  assert.match(server, /youtube_metadata_json JSONB/);
  assert.match(server, /video_processing_requested BOOLEAN DEFAULT FALSE/);
  assert.match(server, /async function ensureDefaultAssignmentPrompts/);
  assert.match(server, /app\.get\('\/api\/bna\/assignments'/);
  assert.match(server, /app\.post\('\/api\/bna\/assignments'/);
  assert.match(server, /app\.post\('\/api\/bna\/assignments\/youtube-metadata'/);
  assert.match(server, /app\.post\('\/api\/bna\/assignments\/:id\/actions'/);
  assert.match(server, /publish_schedule/);
  assert.match(server, /regenerate_student_worksheet/);
});

test('Google Classroom and Calendar payloads use the confirmed API fields', () => {
  assert.match(server, /scheduledTime/);
  assert.match(server, /dueDate/);
  assert.match(server, /dueTime/);
  assert.match(server, /youtubeVideo/);
  assert.match(server, /assigneeMode = 'INDIVIDUAL_STUDENTS'/);
  assert.match(server, /individualStudentsOptions/);
  assert.match(server, /googleClassroomService\.createCourseWork/);
  assert.match(server, /googleCalendarService\.insertEvent/);
  assert.match(server, /googleCalendarService\.updateEvent/);
  assert.match(server, /synced\.data\?\.id/);
  assert.doesNotMatch(server, /created\.data\?\.id/);
  assert.match(googleIntegrations, /classroom\.courses\.courseWork\.create/);
  assert.match(googleIntegrations, /google\.classroom\(\{ version: 'v1', auth \}\)/);
  assert.match(googleIntegrations, /google\.calendar\(\{ version: 'v3', auth \}\)/);
  assert.match(googleIntegrations, /events\.insert/);
  assert.match(googleIntegrations, /events\.update/);
  assert.match(server, /calendarId: item\.calendarId/);
  assert.match(server, /https:\/\/developers\.google\.com\/calendar\/api\/v3\/reference\/events\/insert/);
  assert.match(envExample, /classroom\.coursework\.students/);
  assert.match(envExample, /calendar\.events/);
});

test('Google OAuth is role-scoped and saved through a connection abstraction', () => {
  assert.match(googleIntegrations, /GOOGLE_CONNECTION_ROLES/);
  assert.match(googleIntegrations, /admin_teacher/);
  assert.match(googleIntegrations, /student/);
  assert.match(googleIntegrations, /parent/);
  assert.match(server, /CREATE TABLE IF NOT EXISTS bna_google_connections/);
  assert.match(server, /app\.get\('\/api\/google\/connections\/status'/);
  assert.match(server, /app\.get\('\/api\/google\/classroom\/courses'/);
  assert.match(server, /app\.get\('\/api\/google\/calendar\/events'/);
});

test('assignments support YouTube metadata, optional yt-dlp jobs, and schedule items', () => {
  assert.match(server, /function isValidYoutubeAssignmentUrl/);
  assert.match(server, /async function fetchYoutubeMetadata/);
  assert.match(server, /youtube\.com\/oembed/);
  assert.match(server, /BNA_YTDLP_ENABLED/);
  assert.match(server, /YTDLP_BINARY/);
  assert.match(server, /createVideoProcessingJobForAssignment/);
  assert.match(server, /runVideoProcessingJob/);
  assert.match(server, /queue_video_download/);
  assert.match(server, /assignmentVideoProcessingRequestedFromBody/);
  assert.match(server, /shouldQueueAssignmentVideoProcessing/);
  assert.match(server, /replaceScheduleItemsForAssignment/);
  assert.match(server, /monday/);
  assert.match(server, /every\\s\+morning/);
  assert.match(server, /lessons\?/);
  assert.match(googleIntegrations, /youtubeDownloader: 'yt-dlp'/);
  assert.match(envExample, /BNA_YTDLP_ENABLED=false/);
});

test('Operations exposes assignment creation, prompt patching, student patches, and Google preview', () => {
  assert.match(operations, /getAssignments\(filters = \{\}\)/);
  assert.match(operations, /\{ id: 'assignments', label: 'Assignments' \}/);
  assert.match(operations, /function renderStudentAssignmentsView/);
  assert.match(operations, /function renderInternalClassroomBoard/);
  assert.match(operations, /function renderAssignmentCalendar/);
  assert.match(operations, /function assignmentScheduleEntries/);
  assert.match(operations, /data-classroom-board/);
  assert.match(operations, /data-assignment-calendar/);
  assert.match(operations, /classroom-lanes/);
  assert.match(operations, /assignment-calendar-grid/);
  assert.match(operations, /Internal Classroom/);
  assert.match(operations, /Internal schedule/);
  assert.match(operations, /function focusAssignmentCard/);
  assert.match(operations, /id="assignment-card-\$\{Number\(assignment\.id\)\}"/);
  assert.match(operations, /Worksheet Prompt Patch/);
  assert.match(operations, /Fetch Metadata/);
  assert.match(operations, /Google Classroom sync/);
  assert.match(operations, /Google Calendar sync/);
  assert.match(operations, /Optional download\/process video/);
  assert.match(operations, /assignmentVideoProcessing-/);
  assert.match(operations, /video_processing_requested: videoProcessingRequested/);
  assert.match(operations, /payload\.video_processing_requested = Boolean\(videoToggle\.checked\)/);
  assert.match(operations, /short_answer/);
  assert.match(operations, /multiple_choice/);
  assert.match(operations, /parent_discussion_questions/);
  assert.match(operations, /teacher_review_version/);
  assert.match(operations, /age_level_adjustment/);
  assert.match(operations, /Apply Correction \+ Regenerate/);
  assert.match(operations, /Assignment Prompt Patch/);
  assert.match(operations, /Parent \/ Teacher Instruction Patch/);
  assert.match(operations, /Per-student prompt patch/);
  assert.match(operations, /Patch instruction \/ level note/);
  assert.match(operations, /Student worksheet/);
  assert.match(operations, /Regenerate for this student/);
  assert.match(operations, /Prompt \/ Generation Record/);
  assert.match(operations, /Queue Video Processing/);
  assert.match(operations, /Preview Resolved Prompt/);
  assert.match(operations, /Preview Google Payload/);
  assert.match(operations, /Publish\/Schedule/);
  assert.match(operations, /Live Google Sync/);
  assert.match(operations, /function fetchAssignmentMetadata/);
  assert.match(operations, /function publishAssignmentSchedule/);
  assert.match(operations, /function regenerateAssignmentStudentWorksheet/);
  assert.match(operations, /function syncAssignmentGoogle/);
  assert.match(operations, /function queueAssignmentVideoDownload/);
  assert.match(operations, /Type SYNC_GOOGLE/);
  assert.match(operations, /confirm: 'SYNC_GOOGLE'/);
});

test('student and parent portals render assignment payloads', () => {
  assert.match(server, /const assignments = await getAssignmentsForStudentPortal/);
  assert.match(student, /id="assignmentsSection"/);
  assert.match(student, /function renderAssignments\(assignments = \[\]\)/);
  assert.match(student, /classroom_alternate_link/);
  assert.match(student, /calendar_html_link/);
  assert.match(student, /google_classroom_status/);
  assert.match(student, /google_calendar_status/);
  assert.match(parent, /function renderAssignments\(items = \[\]\)/);
  assert.match(parent, /const assignments = Array\.isArray\(studentPayload\.assignments\)/);
  assert.match(parent, /google_classroom_status/);
  assert.match(parent, /google_calendar_status/);
  assert.match(parent, /<h3>\$\{escapeHtml\(t\('assignments'\)\)\}<\/h3>/);
});
