const assert = require('node:assert/strict');
const fs = require('node:fs');
const test = require('node:test');

test('One Time focused landing copy uses launch funnel offer and safe CTAs', () => {
  const html = fs.readFileSync('public/one-time/index.html', 'utf8');

  assert.match(html, /One Time Mishnayos/);
  assert.match(html, /Give your son a love for Torah you never thought possible/);
  assert.match(html, /Sign Up Now/);
  assert.match(html, /data-signup-modal/);
  assert.match(html, /data-signup-form/);
  assert.match(html, /name="parent_name"/);
  assert.match(html, /name="email"/);
  assert.match(html, /name="phone"/);
  assert.doesNotMatch(html, /name="student_name"|name="studentName"|name="learner_name"|name="learnerName"/);
  assert.match(html, /preferred_class_format/);
  assert.match(html, /data-continue-onboarding/);
  assert.match(html, /window\.location\.href = `\/one-time-preview\?\$\{params\.toString\(\)\}`/);
  assert.match(html, /Member Login/);
  assert.match(html, /Join free until Rosh Hashanah/);
  assert.match(html, /Meet Rabbi Eli Scheller/);
  assert.match(html, /As seen through Jewish media and learning platforms/);
  assert.match(html, /Teaching Torah Across The World/);
  assert.match(html, /How It Works/);
  assert.match(html, /\/one-time\/privacy\.html/);
  assert.match(html, /\/one-time\/terms\.html/);
  assert.doesNotMatch(html, /TODO: replace with final hero video\/image/);
  assert.doesNotMatch(html, /hero-media-placeholder|image-placeholder/);
  assert.doesNotMatch(html, /approved Zoom details/);
  assert.doesNotMatch(html, /signup-strip/);
  assert.doesNotMatch(html, /Join the Free Class/);
  assert.doesNotMatch(html, /Save My Spot/);
  assert.doesNotMatch(html, /See How It Works/);
  assert.doesNotMatch(html, /WhatsApp Robot Scheller/);
  assert.doesNotMatch(html, /Quick answers before you start/);
  assert.doesNotMatch(html, /FAQ/);
  assert.doesNotMatch(html, /class="announcement"/);
  assert.doesNotMatch(html, /class="ticker"/);
  assert.doesNotMatch(html, />Region</);
  assert.doesNotMatch(html, />Notes</);
  assert.doesNotMatch(html, /parent access next steps/i);
  assert.doesNotMatch(html, /Parent portal setup instructions/i);
  assert.doesNotMatch(html, /private asset library/i);
  assert.doesNotMatch(html, /server-backed/i);
  assert.doesNotMatch(html, /video ID/i);
  assert.doesNotMatch(html, /player\.vimeo\.com/);
  assert.doesNotMatch(html, /approved launch configuration/i);
  assert.doesNotMatch(html, /No charge or external send was performed/i);
  assert.doesNotMatch(html, /raw external page/i);
  assert.doesNotMatch(html, /CAPTCHA/i);
  assert.doesNotMatch(html, /\/provider\.html\?review=one-time/);
  assert.doesNotMatch(html, /\/parent\.html\?review=one-time/);
  assert.doesNotMatch(html, /\/student\.html\?review=one-time/);
  assert.doesNotMatch(html, /TEST-ONETIME-REVIEW-ACCESS/);
  assert.doesNotMatch(html, /Academy\s*&\s*Hotline/i);
  assert.doesNotMatch(html, /Academy and Hotline/i);
});

test('One Time focused offer route and registries are declared', () => {
  const server = fs.readFileSync('server.js', 'utf8');
  const operations = fs.readFileSync('public/operations.html', 'utf8');
  const routeRegistry = JSON.parse(fs.readFileSync('ops/route-registry.json', 'utf8'));
  const actionRegistry = JSON.parse(fs.readFileSync('ops/action-registry.json', 'utf8'));

  assert.match(server, /'\/one-time\/mishnayos'/);
  assert.match(server, /function isOneTimeSingleTenantRuntime\(\)/);
  assert.match(server, /app\.get\(\['\/', '\/index\.html', '\/public', '\/public\/'\]/);
  assert.match(server, /INSTANCE_RUNTIME_FLAGS\.single_tenant/);
  assert.match(server, /'\/one-time\/'/);
  assert.match(operations, /function updateDocumentTitleForWorkspace\(\)/);
  assert.match(operations, /currentWorkspaceIsOneTime\(\)[\s\S]*document\.title = `\$\{workspaceName\} - Operations`/);

  const routes = new Set(routeRegistry.routes.map((route) => route.route));
  assert.ok(routes.has('/one-time'));
  assert.ok(routes.has('/public'));
  assert.ok(routes.has('/one-time/mishnayos'));
  assert.ok(routes.has('/one-time/privacy.html'));
  assert.ok(routes.has('/one-time/terms.html'));
  assert.ok(routes.has('/one-time-preview'));

  const actions = new Set(actionRegistry.actions.map((action) => action.action_id));
  assert.ok(actions.has('ACTION-ONETIME-JOIN-SHIR-CTA'));
  assert.ok(actions.has('ACTION-ONETIME-INTEREST-FORM'));
  assert.ok(actions.has('ACTION-ONETIME-SIGNUP-CONTINUE-ONBOARDING'));
  assert.ok(actions.has('ACTION-ONETIME-PUBLIC-MOBILE-MENU'));
  assert.ok(actions.has('ACTION-ONETIME-TEACHING-CAROUSEL-PREV'));
  assert.ok(actions.has('ACTION-ONETIME-TEACHING-CAROUSEL-NEXT'));
  assert.ok(actions.has('ACTION-ONETIME-TEACHING-CAROUSEL-PAUSE'));
  assert.ok(actions.has('ACTION-ONETIME-MEMBER-LOGIN-LINK'));
  const joinAction = actionRegistry.actions.find((action) => action.action_id === 'ACTION-ONETIME-JOIN-SHIR-CTA');
  assert.match(joinAction.selector_hint, /data-signup-trigger/);
  assert.match(joinAction.expected_behavior, /signup modal/);
  const formAction = actionRegistry.actions.find((action) => action.action_id === 'ACTION-ONETIME-INTEREST-FORM');
  assert.match(formAction.expected_behavior, /email/i);
  assert.match(formAction.expected_behavior, /CRM lead/i);
  assert.match(formAction.expected_behavior, /no student name/i);
  assert.match(formAction.expected_behavior, /no checkout/i);
  const continueAction = actionRegistry.actions.find((action) => action.action_id === 'ACTION-ONETIME-SIGNUP-CONTINUE-ONBOARDING');
  assert.match(continueAction.expected_behavior, /one-time-preview/);
});
