-- REQ-20260618-111 safe repeatable seed SQL. TEST_REQ022 fixture prefix is preserved for compatibility.
-- This script starts by cleaning prior TEST_REQ022 rows for the same fixture family.
BEGIN;
DELETE FROM bna_helper_tool_audit_log WHERE request_id LIKE 'TEST_REQ022%' OR args_redacted->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR args_redacted->>'run_id' = '20260618_local';
DELETE FROM bna_assignment_students ast USING bna_assignments a WHERE ast.assignment_id = a.id AND (a.metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR a.title LIKE 'TEST_REQ022%');
DELETE FROM bna_assignments WHERE metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR title LIKE 'TEST_REQ022%';
DELETE FROM bna_devices d USING bna_students s WHERE d.student_id = s.id AND ('test:req022' = ANY(COALESCE(s.tags, ARRAY[]::text[])) OR s.name LIKE 'TEST_REQ022%');
DELETE FROM bna_calendar_events WHERE metadata_json->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR title LIKE 'TEST_REQ022%';
DELETE FROM bna_learning_communities WHERE metadata_json->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR community_key LIKE 'test_req022%';
DELETE FROM bna_automations WHERE metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR automation_key LIKE 'test_req022%';
DELETE FROM bna_content_jobs WHERE title LIKE 'TEST_REQ022%' OR notes LIKE '%req022_safe_repeatable_seed_v1%';
DELETE FROM bna_tasks WHERE ai_parsed->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR title LIKE 'TEST_REQ022%';
DELETE FROM bna_project_members WHERE metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR person_name LIKE 'TEST_REQ022%';
DELETE FROM bna_students WHERE 'test:req022' = ANY(COALESCE(tags, ARRAY[]::text[])) OR name LIKE 'TEST_REQ022%' OR student_access_code = 'TEST_REQ022_20260618_LOCAL_STUDENT_ACCESS';
DELETE FROM bna_workspaces WHERE metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR "key" LIKE 'test_req022%';
DELETE FROM bna_projects WHERE metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' OR project_key LIKE 'test_req022%';

INSERT INTO bna_projects (project_key, name, short_name, description, status, metadata) VALUES ('test_req022_20260618_local_school', 'TEST_REQ022_20260618_local_School Project', 'school', 'REQ-022 isolated TEST seed project', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"project","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","workspace_type":"school"}'::jsonb) ON CONFLICT (project_key) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, description = EXCLUDED.description, metadata = COALESCE(bna_projects.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_projects (project_key, name, short_name, description, status, metadata) VALUES ('test_req022_20260618_local_provider', 'TEST_REQ022_20260618_local_Provider Project', 'service_provider', 'REQ-022 isolated TEST seed project', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"project","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","workspace_type":"service_provider"}'::jsonb) ON CONFLICT (project_key) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, description = EXCLUDED.description, metadata = COALESCE(bna_projects.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_projects (project_key, name, short_name, description, status, metadata) VALUES ('test_req022_20260618_local_family', 'TEST_REQ022_20260618_local_Family Project', 'family', 'REQ-022 isolated TEST seed project', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"project","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","workspace_type":"family"}'::jsonb) ON CONFLICT (project_key) DO UPDATE SET name = EXCLUDED.name, short_name = EXCLUDED.short_name, description = EXCLUDED.description, metadata = COALESCE(bna_projects.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_workspaces (project_id, "key", workspace_key, name, type, status, metadata) SELECT p.id, 'test_req022_20260618_local_school_workspace', 'test_req022_20260618_local_school_workspace', 'TEST_REQ022_20260618_local_School Workspace', 'school', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_school"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school' ON CONFLICT ("key") DO UPDATE SET project_id = EXCLUDED.project_id, workspace_key = EXCLUDED.workspace_key, name = EXCLUDED.name, type = EXCLUDED.type, status = EXCLUDED.status, metadata = COALESCE(bna_workspaces.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_workspaces (project_id, "key", workspace_key, name, type, status, metadata) SELECT p.id, 'test_req022_20260618_local_provider_workspace', 'test_req022_20260618_local_provider_workspace', 'TEST_REQ022_20260618_local_Provider Workspace', 'service_provider', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_provider"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_provider' ON CONFLICT ("key") DO UPDATE SET project_id = EXCLUDED.project_id, workspace_key = EXCLUDED.workspace_key, name = EXCLUDED.name, type = EXCLUDED.type, status = EXCLUDED.status, metadata = COALESCE(bna_workspaces.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_workspaces (project_id, "key", workspace_key, name, type, status, metadata) SELECT p.id, 'test_req022_20260618_local_family_workspace', 'test_req022_20260618_local_family_workspace', 'TEST_REQ022_20260618_local_Family Workspace', 'family', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_family"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_family' ON CONFLICT ("key") DO UPDATE SET project_id = EXCLUDED.project_id, workspace_key = EXCLUDED.workspace_key, name = EXCLUDED.name, type = EXCLUDED.type, status = EXCLUDED.status, metadata = COALESCE(bna_workspaces.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_project_members (project_id, person_name, role, access_level, active, metadata) SELECT p.id, 'TEST_REQ022_20260618_local_Admin', 'admin', 'manager', TRUE, '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace_role","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_school"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school' ON CONFLICT (project_id, person_name) DO UPDATE SET role = EXCLUDED.role, access_level = EXCLUDED.access_level, active = TRUE, metadata = COALESCE(bna_project_members.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_project_members (project_id, person_name, role, access_level, active, metadata) SELECT p.id, 'TEST_REQ022_20260618_local_Rabbi Provider', 'teacher', 'owner', TRUE, '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace_role","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_provider"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_provider' ON CONFLICT (project_id, person_name) DO UPDATE SET role = EXCLUDED.role, access_level = EXCLUDED.access_level, active = TRUE, metadata = COALESCE(bna_project_members.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_project_members (project_id, person_name, role, access_level, active, metadata) SELECT p.id, 'TEST_REQ022_20260618_local_Parent', 'parent', 'member', TRUE, '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"workspace_role","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_family"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_family' ON CONFLICT (project_id, person_name) DO UPDATE SET role = EXCLUDED.role, access_level = EXCLUDED.access_level, active = TRUE, metadata = COALESCE(bna_project_members.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_at = NOW();
INSERT INTO bna_students (project_id, name, name_en, name_he, parent_name, parent_email, age, grade, current_school, student_access_code, student_access_enabled, status, tags, notes) SELECT p.id, 'TEST_REQ022_20260618_local_Student', 'TEST_REQ022_20260618_local_Student', 'תלמיד בדיקה', 'TEST_REQ022_20260618_local_Parent', 'test_req022_20260618_local_parent@example.test', 12, 'TEST', 'REQ-022 fixture school', 'TEST_REQ022_20260618_LOCAL_STUDENT_ACCESS', TRUE, 'active', ARRAY['test:req022', 'test-run:20260618_local', 'hebrew:fixture'], 'req022_safe_repeatable_seed_v1 safe Hebrew/student fixture' FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school' ON CONFLICT (student_access_code) DO UPDATE SET project_id = EXCLUDED.project_id, name = EXCLUDED.name, name_en = EXCLUDED.name_en, name_he = EXCLUDED.name_he, parent_name = EXCLUDED.parent_name, parent_email = EXCLUDED.parent_email, tags = EXCLUDED.tags, notes = EXCLUDED.notes, updated_at = NOW();
INSERT INTO bna_devices (student_id, device_name, platform, provider, provider_device_id, status, notes, metadata) SELECT s.id, 'TEST_REQ022_20260618_local_Tablet', 'web', 'mock', 'test_req022_20260618_local_device', 'accountability_only', 'REQ-022 fixture device; no provider call', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"student_device","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix"}'::jsonb FROM bna_students s WHERE s.student_access_code = 'TEST_REQ022_20260618_LOCAL_STUDENT_ACCESS';
INSERT INTO bna_assignments (project_id, title, instructions, source_type, language_mode, worksheet_type, schedule_text, schedule_plan, sync_mode, status, created_by, metadata) SELECT p.id, 'TEST_REQ022_20260618_local_Hebrew Assignment', 'TEST assignment for Hebrew/RTL and student detail scoping.', 'manual', 'hebrew', 'reflection', 'Tomorrow 10:00', '{"dry_run":true,"no_google_write":true}'::jsonb, 'app_only', 'draft', 'req022_seed', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"assignment","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","no_google_write":true}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school';
INSERT INTO bna_assignment_students (assignment_id, student_id, student_name, status, sync_status, metadata) SELECT a.id, s.id, s.name, 'assigned', 'not_requested', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"assignment_student","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix"}'::jsonb FROM bna_assignments a CROSS JOIN bna_students s WHERE a.metadata->>'req022_seed_key' = 'req022_safe_repeatable_seed_v1' AND s.student_access_code = 'TEST_REQ022_20260618_LOCAL_STUDENT_ACCESS';
INSERT INTO bna_tasks (title, notes, stage, category, urgency, source, ai_parsed, created_by, assigned_to, project_id) SELECT 'TEST_REQ022_20260618_local_Task', 'REQ-022 task fixture for Operations Tasks lane.', 'assigned', 'operations', 'this_week', 'manual', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"task","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix"}'::jsonb, 'req022_seed', 'Codex', p.id FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school';
INSERT INTO bna_tasks (title, notes, stage, category, urgency, source, ai_parsed, created_by, assigned_to, project_id) SELECT 'TEST_REQ022_20260618_local_Decision', 'REQ-022 decision fixture represented as needs_decision task.', 'needs_decision', 'operations', 'today', 'manual', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"decision","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","decision_fixture":true}'::jsonb, 'req022_seed', 'Shloimie', p.id FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school';
INSERT INTO bna_calendar_events (workspace_key, related_type, title, description, start_at, end_at, status, visibility, source, metadata_json, created_by) VALUES ('test_req022_20260618_local_school_workspace', 'task', 'TEST_REQ022_20260618_local_Calendar Check-in', 'REQ-022 internal calendar fixture; no Google sync.', NOW() + INTERVAL '1 day', NOW() + INTERVAL '1 day 30 minutes', 'scheduled', 'internal', 'manual', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"calendar","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","no_google_write":true}'::jsonb, 'req022_seed');
INSERT INTO bna_content_jobs (title, source_type, caption, status, transcript_text, parse_json, notes) VALUES ('TEST_REQ022_20260618_local_Content Research', 'manual', 'REQ-022 reusable teaching-content fixture', 'needs_approval', 'TEST transcript for scoped content/research fixture.', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"content_research","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","project_key":"test_req022_20260618_local_school"}'::jsonb, 'req022_safe_repeatable_seed_v1 project_key=test_req022_20260618_local_school');
INSERT INTO bna_learning_communities (workspace_key, project_id, community_key, title, description, owner_name, visibility, status, metadata_json) SELECT 'test_req022_20260618_local_school_workspace', p.id, 'test_req022_20260618_local_community', 'TEST_REQ022_20260618_local_Community', 'REQ-022 scoped community fixture', 'Rabbi Shloimie', 'members', 'active', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"community","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix"}'::jsonb FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school' ON CONFLICT (workspace_key, community_key) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, metadata_json = COALESCE(bna_learning_communities.metadata_json, '{}'::jsonb) || EXCLUDED.metadata_json, updated_at = NOW();
INSERT INTO bna_automations (automation_key, name, summary, description, package_key, package_name, service_key, service_name, scope_type, project_id, owner, responsible_person, status, automation_type, trigger_type, trigger_label, channel, audience, permissions, setup_blockers, config, metadata, created_by, updated_by) SELECT 'test_req022_20260618_local_automation', 'TEST_REQ022_20260618_local_Automation Draft', 'REQ-022 local-only automation fixture', 'Dry-run metadata only; no external handler.', 'test', 'REQ-022 Test Package', 'local', 'Local only', 'project', p.id, 'Codex', 'Shloimie', 'draft', 'workflow', 'manual', 'Manual fixture trigger', 'dashboard', 'BNA Operations', '{"registry_edits_only":true,"no_external_write":true}'::jsonb, '["Fixture only; do not enable live handler."]'::jsonb, '{"dry_run":true}'::jsonb, '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"automation","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","no_external_write":true}'::jsonb, 'req022_seed', 'req022_seed' FROM bna_projects p WHERE p.project_key = 'test_req022_20260618_local_school' ON CONFLICT (automation_key) DO UPDATE SET name = EXCLUDED.name, summary = EXCLUDED.summary, description = EXCLUDED.description, status = EXCLUDED.status, permissions = COALESCE(bna_automations.permissions, '{}'::jsonb) || EXCLUDED.permissions, setup_blockers = EXCLUDED.setup_blockers, metadata = COALESCE(bna_automations.metadata, '{}'::jsonb) || EXCLUDED.metadata, updated_by = EXCLUDED.updated_by, updated_at = NOW();
INSERT INTO bna_helper_tool_audit_log (request_id, client_request_id, plan_id, tool_call_id, conversation_id, message_hash, tool_name, action_label, risk_level, status, requires_confirmation, confirmed, user_name, user_role, workspace_key, project_key, record_type, record_id, page_context_redacted, args_redacted, result_redacted, error_message) VALUES ('TEST_REQ022_20260618_local_helper_request', 'test_req022_20260618_local_client', 'TEST_REQ022_20260618_local_helper_plan', 'TEST_REQ022_20260618_local_helper_action', 'test_req022_20260618_local_conversation', 'test_req022_20260618_local_message_hash', 'open_operations_view', 'TEST_REQ022_20260618_local_Helper Audit', 'low', 'planned', FALSE, FALSE, 'REQ-022 Seed', 'one_time_admin', 'test_req022_20260618_local_school_workspace', 'test_req022_20260618_local_school', 'seed_fixture', '20260618_local', '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"helper_page_context","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","route":"/operations"}'::jsonb, '{"req022_seed_key":"req022_safe_repeatable_seed_v1","seed_prefix":"TEST_REQ022","run_id":"20260618_local","area":"helper_args","external_write_performed":false,"cleanup_selector":"metadata.req022_seed_key + TEST_REQ022 prefix","workspace_key":"test_req022_20260618_local_school_workspace","project_key":"test_req022_20260618_local_school"}'::jsonb, '{"dry_run":true,"no_external_write":true}'::jsonb, NULL);
COMMIT;
