import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Plus, Trash2, Edit2, Eye, EyeOff, Upload, Image, Loader2, ChevronUp, ChevronDown, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Banner = {
  id: string;
  title: string;
  subtitle: string | null;
  imageUrl: string | null;
  videoId: string | null;
  isActive: boolean;
  isAutoGenerated: boolean;
  displayOrder: number;
  createdAt: string;
};

function imageDisplayUrl(bannerId: string, imageUrl: string | null): string | null {
  if (!imageUrl) return null;
  if (imageUrl.startsWith("/objects/")) return `/api/banners/${bannerId}/image`;
  return imageUrl;
}

export default function BannersManagement() {
  const { toast } = useToast();
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [editingBanner, setEditingBanner] = useState<Banner | null>(null);
  const [uploadingImageFor, setUploadingImageFor] = useState<string | null>(null);

  const [form, setForm] = useState({ title: "", subtitle: "", imageUrl: "", videoId: "" });

  const { data: banners = [], isLoading } = useQuery<Banner[]>({
    queryKey: ["/api/admin/banners"],
  });

  const createMutation = useMutation({
    mutationFn: (data: typeof form) => apiRequest("POST", "/api/admin/banners", data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      setShowAddDialog(false);
      setForm({ title: "", subtitle: "", imageUrl: "", videoId: "" });
      toast({ title: "Slide added!" });
    },
    onError: () => toast({ title: "Failed to add slide", variant: "destructive" }),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: Partial<Banner> }) =>
      apiRequest("PUT", `/api/admin/banners/${id}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      setEditingBanner(null);
      toast({ title: "Slide updated!" });
    },
    onError: () => toast({ title: "Failed to update", variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/banners/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      toast({ title: "Slide deleted" });
    },
  });

  const toggleMutation = useMutation({
    mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) =>
      apiRequest("PUT", `/api/admin/banners/${id}`, { isActive }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] }),
  });

  const reorderMutation = useMutation({
    mutationFn: (ids: string[]) => apiRequest("POST", "/api/admin/banners/reorder", { ids }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] }),
  });

  const handleImageUpload = async (bannerId: string, file: File) => {
    setUploadingImageFor(bannerId);
    try {
      const fd = new FormData();
      fd.append("image", file);
      const res = await fetch(`/api/admin/banners/${bannerId}/image`, {
        method: "POST",
        body: fd,
        credentials: "include",
      });
      if (!res.ok) throw new Error();
      await queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      toast({ title: "Image uploaded!" });
    } catch {
      toast({ title: "Image upload failed", variant: "destructive" });
    } finally {
      setUploadingImageFor(null);
    }
  };

  const moveUp = (idx: number) => {
    if (idx === 0) return;
    const ids = banners.map(b => b.id);
    [ids[idx - 1], ids[idx]] = [ids[idx], ids[idx - 1]];
    reorderMutation.mutate(ids);
  };

  const moveDown = (idx: number) => {
    if (idx === banners.length - 1) return;
    const ids = banners.map(b => b.id);
    [ids[idx], ids[idx + 1]] = [ids[idx + 1], ids[idx]];
    reorderMutation.mutate(ids);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Banner Slideshow</h1>
          <p className="text-muted-foreground mt-1">Manage the slides shown at the top of the subscriber dashboard</p>
        </div>
        <Button onClick={() => setShowAddDialog(true)} data-testid="button-add-slide">
          <Plus className="h-4 w-4 mr-2" />
          Add Slide
        </Button>
      </div>

      {isLoading && (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      )}

      {!isLoading && banners.length === 0 && (
        <Card>
          <CardContent className="py-16 text-center">
            <Image className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-muted-foreground">No slides yet. Add one to get started!</p>
            <Button className="mt-4" onClick={() => setShowAddDialog(true)}>Add First Slide</Button>
          </CardContent>
        </Card>
      )}

      <div className="space-y-3">
        {banners.map((banner, idx) => {
          const thumb = imageDisplayUrl(banner.id, banner.imageUrl);
          const isUploading = uploadingImageFor === banner.id;
          return (
            <Card key={banner.id} className={banner.isActive ? "" : "opacity-60"}>
              <CardContent className="p-4">
                <div className="flex items-center gap-4">
                  {/* Thumbnail */}
                  <div className="relative w-20 h-14 rounded-lg overflow-hidden bg-muted flex-shrink-0 flex items-center justify-center border border-border">
                    {thumb ? (
                      <img src={thumb} alt={banner.title} className="w-full h-full object-cover" />
                    ) : (
                      <Image className="h-6 w-6 text-muted-foreground" />
                    )}
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <span className="font-semibold text-sm truncate">{banner.title}</span>
                      {banner.isAutoGenerated && (
                        <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                          <Sparkles className="h-2.5 w-2.5 mr-1" />Auto
                        </Badge>
                      )}
                      {!banner.isActive && <Badge variant="outline" className="text-[10px] px-1.5 py-0">Hidden</Badge>}
                    </div>
                    {banner.subtitle && <p className="text-xs text-muted-foreground truncate">{banner.subtitle}</p>}
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-1 shrink-0">
                    {/* Reorder */}
                    <div className="flex flex-col">
                      <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => moveUp(idx)} disabled={idx === 0}>
                        <ChevronUp className="h-3 w-3" />
                      </Button>
                      <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => moveDown(idx)} disabled={idx === banners.length - 1}>
                        <ChevronDown className="h-3 w-3" />
                      </Button>
                    </div>

                    {/* Image upload */}
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      title="Upload image"
                      disabled={isUploading}
                      onClick={() => {
                        const input = document.createElement("input");
                        input.type = "file";
                        input.accept = "image/*";
                        input.onchange = (e) => {
                          const file = (e.target as HTMLInputElement).files?.[0];
                          if (file) handleImageUpload(banner.id, file);
                        };
                        input.click();
                      }}
                      data-testid={`button-upload-image-${banner.id}`}
                    >
                      {isUploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
                    </Button>

                    {/* Toggle active */}
                    <Switch
                      checked={!!banner.isActive}
                      onCheckedChange={(checked) => toggleMutation.mutate({ id: banner.id, isActive: checked })}
                      data-testid={`switch-active-${banner.id}`}
                    />

                    {/* Edit */}
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      onClick={() => setEditingBanner(banner)}
                      data-testid={`button-edit-${banner.id}`}
                    >
                      <Edit2 className="h-4 w-4" />
                    </Button>

                    {/* Delete */}
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                      onClick={() => deleteMutation.mutate(banner.id)}
                      disabled={deleteMutation.isPending}
                      data-testid={`button-delete-${banner.id}`}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Add Slide Dialog */}
      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Add Banner Slide</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="slide-title">Headline *</Label>
              <Input
                id="slide-title"
                placeholder="e.g. Pesach Haggadah now available!"
                value={form.title}
                onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                data-testid="input-slide-title"
              />
            </div>
            <div>
              <Label htmlFor="slide-subtitle">Subtext</Label>
              <Textarea
                id="slide-subtitle"
                placeholder="e.g. Get your copy today — beautiful and inspiring!"
                value={form.subtitle}
                onChange={e => setForm(f => ({ ...f, subtitle: e.target.value }))}
                rows={2}
                data-testid="textarea-slide-subtitle"
              />
            </div>
            <div>
              <Label htmlFor="slide-image">Image URL (optional)</Label>
              <Input
                id="slide-image"
                placeholder="https://... (you can also upload after creating)"
                value={form.imageUrl}
                onChange={e => setForm(f => ({ ...f, imageUrl: e.target.value }))}
                data-testid="input-slide-image"
              />
              <p className="text-xs text-muted-foreground mt-1">Paste an image URL, or upload a file after creating the slide.</p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAddDialog(false)}>Cancel</Button>
            <Button
              onClick={() => createMutation.mutate(form)}
              disabled={!form.title.trim() || createMutation.isPending}
              data-testid="button-create-slide"
            >
              {createMutation.isPending && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
              Add Slide
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Slide Dialog */}
      {editingBanner && (
        <Dialog open={true} onOpenChange={() => setEditingBanner(null)}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Edit Slide</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Headline *</Label>
                <Input
                  value={editingBanner.title}
                  onChange={e => setEditingBanner(b => b ? ({ ...b, title: e.target.value }) : b)}
                  data-testid="input-edit-title"
                />
              </div>
              <div>
                <Label>Subtext</Label>
                <Textarea
                  value={editingBanner.subtitle || ""}
                  onChange={e => setEditingBanner(b => b ? ({ ...b, subtitle: e.target.value }) : b)}
                  rows={2}
                  data-testid="textarea-edit-subtitle"
                />
              </div>
              <div>
                <Label>Image URL</Label>
                <Input
                  value={editingBanner.imageUrl || ""}
                  onChange={e => setEditingBanner(b => b ? ({ ...b, imageUrl: e.target.value }) : b)}
                  placeholder="https://..."
                  data-testid="input-edit-image"
                />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setEditingBanner(null)}>Cancel</Button>
              <Button
                onClick={() => updateMutation.mutate({ id: editingBanner.id, data: { title: editingBanner.title, subtitle: editingBanner.subtitle, imageUrl: editingBanner.imageUrl } })}
                disabled={!editingBanner.title.trim() || updateMutation.isPending}
                data-testid="button-save-edit"
              >
                {updateMutation.isPending && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
                Save Changes
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}
