import { useState, useRef } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Plus, Trash2, Edit2, Upload, Image, Loader2, ChevronUp, ChevronDown, Sparkles, X, Clock, Calendar } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Banner = {
  id: string;
  title: string;
  subtitle: string | null;
  imageUrl: string | null;
  videoId: string | null;
  isActive: boolean;
  isAutoGenerated: boolean;
  displayOrder: number;
  expiresAt: string | null;
  createdAt: string;
};

function imageDisplayUrl(bannerId: string, imageUrl: string | null): string | null {
  if (!imageUrl) return null;
  if (imageUrl.startsWith("/objects/")) return `/api/banners/${bannerId}/image`;
  return imageUrl;
}

function daysUntil(dateStr: string | null): number | null {
  if (!dateStr) return null;
  const diff = new Date(dateStr).getTime() - Date.now();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}

function ExpiryBadge({ expiresAt }: { expiresAt: string | null }) {
  if (!expiresAt) return null;
  const days = daysUntil(expiresAt);
  if (days === null) return null;
  if (days <= 0) return <Badge variant="destructive" className="text-[10px] px-1.5 py-0">Expired</Badge>;
  if (days <= 2) return <Badge className="text-[10px] px-1.5 py-0 bg-orange-500 hover:bg-orange-500">Expires in {days}d</Badge>;
  return <Badge variant="outline" className="text-[10px] px-1.5 py-0 gap-1"><Clock className="h-2.5 w-2.5" />{days}d left</Badge>;
}

const EXPIRY_SHORTCUTS = [
  { label: "3 days", days: 3 },
  { label: "7 days", days: 7 },
  { label: "14 days", days: 14 },
  { label: "30 days", days: 30 },
  { label: "No limit", days: 0 },
];

function addDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 16);
}

export default function BannersManagement() {
  const { toast } = useToast();
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [editingBanner, setEditingBanner] = useState<Banner | null>(null);
  const [uploadingImageFor, setUploadingImageFor] = useState<string | null>(null);

  const emptyForm = { title: "", subtitle: "", imageUrl: "", videoId: "", expiresAt: addDays(7) };
  const [form, setForm] = useState(emptyForm);
  const [pendingImageFile, setPendingImageFile] = useState<File | null>(null);
  const [pendingImagePreview, setPendingImagePreview] = useState<string | null>(null);
  const [editPendingFile, setEditPendingFile] = useState<File | null>(null);

  const { data: banners = [], isLoading } = useQuery<Banner[]>({
    queryKey: ["/api/admin/banners"],
  });

  const uploadImageToNewBanner = async (bannerId: string, file: File) => {
    const fd = new FormData();
    fd.append("image", file);
    const res = await fetch(`/api/admin/banners/${bannerId}/image`, {
      method: "POST",
      body: fd,
      credentials: "include",
    });
    if (!res.ok) throw new Error("Image upload failed");
  };

  const createMutation = useMutation({
    mutationFn: async (data: typeof form) => {
      const payload = { ...data, expiresAt: data.expiresAt ? new Date(data.expiresAt).toISOString() : null };
      const res = await apiRequest("POST", "/api/admin/banners", payload);
      const banner = await res.json();
      if (pendingImageFile) {
        await uploadImageToNewBanner(banner.id, pendingImageFile);
      }
      return banner;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      setShowAddDialog(false);
      setForm(emptyForm);
      setPendingImageFile(null);
      setPendingImagePreview(null);
      toast({ title: "Slide added!" });
    },
    onError: () => toast({ title: "Failed to add slide", variant: "destructive" }),
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<Banner> }) => {
      const payload = { ...data, expiresAt: data.expiresAt ? new Date(data.expiresAt).toISOString() : null };
      const res = await apiRequest("PUT", `/api/admin/banners/${id}`, payload);
      if (editPendingFile) {
        await uploadImageToNewBanner(id, editPendingFile);
      }
      return res;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      setEditingBanner(null);
      setEditPendingFile(null);
      toast({ title: "Slide updated!" });
    },
    onError: () => toast({ title: "Failed to update", variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => apiRequest("DELETE", `/api/admin/banners/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      toast({ title: "Slide deleted" });
    },
  });

  const toggleMutation = useMutation({
    mutationFn: ({ id, isActive }: { id: string; isActive: boolean }) =>
      apiRequest("PUT", `/api/admin/banners/${id}`, { isActive }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] }),
  });

  const reorderMutation = useMutation({
    mutationFn: (ids: string[]) => apiRequest("POST", "/api/admin/banners/reorder", { ids }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] }),
  });

  const handleImageUpload = async (bannerId: string, file: File) => {
    setUploadingImageFor(bannerId);
    try {
      await uploadImageToNewBanner(bannerId, file);
      await queryClient.invalidateQueries({ queryKey: ["/api/admin/banners"] });
      toast({ title: "Image uploaded!" });
    } catch {
      toast({ title: "Image upload failed", variant: "destructive" });
    } finally {
      setUploadingImageFor(null);
    }
  };

  const handleFileSelect = (file: File) => {
    setPendingImageFile(file);
    setPendingImagePreview(URL.createObjectURL(file));
    setForm(f => ({ ...f, imageUrl: "" }));
  };

  const handleEditFileSelect = (file: File) => {
    setEditPendingFile(file);
    setEditingBanner(b => b ? ({ ...b, imageUrl: URL.createObjectURL(file) }) : b);
  };

  const moveUp = (idx: number) => {
    if (idx === 0) return;
    const ids = banners.map(b => b.id);
    [ids[idx - 1], ids[idx]] = [ids[idx], ids[idx - 1]];
    reorderMutation.mutate(ids);
  };

  const moveDown = (idx: number) => {
    if (idx === banners.length - 1) return;
    const ids = banners.map(b => b.id);
    [ids[idx], ids[idx + 1]] = [ids[idx + 1], ids[idx]];
    reorderMutation.mutate(ids);
  };

  const ExpirySection = ({ value, onChange }: { value: string; onChange: (v: string) => void }) => (
    <div>
      <Label className="flex items-center gap-1.5"><Calendar className="h-3.5 w-3.5" />Show Until (Expiry)</Label>
      <div className="flex flex-wrap gap-1.5 mt-1.5 mb-2">
        {EXPIRY_SHORTCUTS.map(s => (
          <Button
            key={s.label}
            type="button"
            size="sm"
            variant="outline"
            className="text-xs h-7"
            onClick={() => onChange(s.days === 0 ? "" : addDays(s.days))}
          >
            {s.label}
          </Button>
        ))}
      </div>
      <Input
        type="datetime-local"
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder="No expiry"
        className="text-sm"
      />
      <p className="text-xs text-muted-foreground mt-1">Leave blank to show indefinitely.</p>
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Banner Slideshow</h1>
          <p className="text-muted-foreground mt-1">Manage the slides shown at the top of the subscriber dashboard</p>
        </div>
        <Button onClick={() => setShowAddDialog(true)} data-testid="button-add-slide">
          <Plus className="h-4 w-4 mr-2" />
          Add Slide
        </Button>
      </div>

      {isLoading && (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      )}

      {!isLoading && banners.length === 0 && (
        <Card>
          <CardContent className="py-16 text-center">
            <Image className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-muted-foreground">No slides yet. Add one to get started!</p>
            <Button className="mt-4" onClick={() => setShowAddDialog(true)}>Add First Slide</Button>
          </CardContent>
        </Card>
      )}

      <div className="space-y-3">
        {banners.map((banner, idx) => {
          const thumb = imageDisplayUrl(banner.id, banner.imageUrl);
          const isUploading = uploadingImageFor === banner.id;
          const expired = banner.expiresAt && daysUntil(banner.expiresAt) !== null && daysUntil(banner.expiresAt)! <= 0;
          return (
            <Card key={banner.id} className={banner.isActive && !expired ? "" : "opacity-60"}>
              <CardContent className="p-4">
                <div className="flex items-center gap-4">
                  <div className="relative w-20 h-14 rounded-lg overflow-hidden bg-muted flex-shrink-0 flex items-center justify-center border border-border">
                    {thumb ? (
                      <img src={thumb} alt={banner.title} className="w-full h-full object-cover" />
                    ) : (
                      <Image className="h-6 w-6 text-muted-foreground" />
                    )}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <span className="font-semibold text-sm truncate">{banner.title}</span>
                      {banner.isAutoGenerated && (
                        <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                          <Sparkles className="h-2.5 w-2.5 mr-1" />Auto
                        </Badge>
                      )}
                      {!banner.isActive && <Badge variant="outline" className="text-[10px] px-1.5 py-0">Hidden</Badge>}
                      <ExpiryBadge expiresAt={banner.expiresAt} />
                    </div>
                    {banner.subtitle && <p className="text-xs text-muted-foreground truncate">{banner.subtitle}</p>}
                  </div>

                  <div className="flex items-center gap-1 shrink-0">
                    <div className="flex flex-col">
                      <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => moveUp(idx)} disabled={idx === 0}>
                        <ChevronUp className="h-3 w-3" />
                      </Button>
                      <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => moveDown(idx)} disabled={idx === banners.length - 1}>
                        <ChevronDown className="h-3 w-3" />
                      </Button>
                    </div>

                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      title="Upload image"
                      disabled={isUploading}
                      onClick={() => {
                        const input = document.createElement("input");
                        input.type = "file";
                        input.accept = "image/*";
                        input.onchange = (e) => {
                          const file = (e.target as HTMLInputElement).files?.[0];
                          if (file) handleImageUpload(banner.id, file);
                        };
                        input.click();
                      }}
                      data-testid={`button-upload-image-${banner.id}`}
                    >
                      {isUploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
                    </Button>

                    <Switch
                      checked={!!banner.isActive}
                      onCheckedChange={(checked) => toggleMutation.mutate({ id: banner.id, isActive: checked })}
                      data-testid={`switch-active-${banner.id}`}
                    />

                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      onClick={() => {
                        setEditingBanner({
                          ...banner,
                          expiresAt: banner.expiresAt ? new Date(banner.expiresAt).toISOString().slice(0, 16) : "",
                        } as any);
                        setEditPendingFile(null);
                      }}
                      data-testid={`button-edit-${banner.id}`}
                    >
                      <Edit2 className="h-4 w-4" />
                    </Button>

                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                      onClick={() => deleteMutation.mutate(banner.id)}
                      disabled={deleteMutation.isPending}
                      data-testid={`button-delete-${banner.id}`}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Add Slide Dialog */}
      <Dialog open={showAddDialog} onOpenChange={(open) => {
        if (!open) { setPendingImageFile(null); setPendingImagePreview(null); setForm(emptyForm); }
        setShowAddDialog(open);
      }}>
        <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add Banner Slide</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="slide-title">Headline *</Label>
              <Input
                id="slide-title"
                placeholder="e.g. Pesach Haggadah now available!"
                value={form.title}
                onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                data-testid="input-slide-title"
              />
            </div>
            <div>
              <Label htmlFor="slide-subtitle">Subtext</Label>
              <Textarea
                id="slide-subtitle"
                placeholder="e.g. A beautiful and inspiring message for the whole family!"
                value={form.subtitle}
                onChange={e => setForm(f => ({ ...f, subtitle: e.target.value }))}
                rows={2}
                data-testid="textarea-slide-subtitle"
              />
            </div>
            <div>
              <Label>Image</Label>
              {pendingImagePreview ? (
                <div className="space-y-2">
                  <div className="relative w-full h-32 rounded-lg overflow-hidden border border-border">
                    <img src={pendingImagePreview} alt="Preview" className="w-full h-full object-cover" />
                    <Button size="icon" variant="destructive" className="absolute top-1 right-1 h-6 w-6" onClick={() => { setPendingImageFile(null); setPendingImagePreview(null); }}>
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">{pendingImageFile?.name}</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="flex gap-2">
                    <Input
                      placeholder="Paste image URL…"
                      value={form.imageUrl}
                      onChange={e => setForm(f => ({ ...f, imageUrl: e.target.value }))}
                      data-testid="input-slide-image"
                    />
                    <Button type="button" variant="outline" className="shrink-0 gap-1.5" onClick={() => {
                      const input = document.createElement("input");
                      input.type = "file";
                      input.accept = "image/*";
                      input.onchange = (e) => {
                        const file = (e.target as HTMLInputElement).files?.[0];
                        if (file) handleFileSelect(file);
                      };
                      input.click();
                    }} data-testid="button-pick-image-file">
                      <Upload className="h-4 w-4" />
                      Upload
                    </Button>
                  </div>
                </div>
              )}
            </div>
            <ExpirySection value={form.expiresAt} onChange={v => setForm(f => ({ ...f, expiresAt: v }))} />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => { setShowAddDialog(false); setPendingImageFile(null); setPendingImagePreview(null); }}>Cancel</Button>
            <Button
              onClick={() => createMutation.mutate(form)}
              disabled={!form.title.trim() || createMutation.isPending}
              data-testid="button-create-slide"
            >
              {createMutation.isPending && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
              Add Slide
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Slide Dialog */}
      {editingBanner && (
        <Dialog open={true} onOpenChange={() => { setEditingBanner(null); setEditPendingFile(null); }}>
          <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Edit Slide</DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Headline *</Label>
                <Input
                  value={editingBanner.title}
                  onChange={e => setEditingBanner(b => b ? ({ ...b, title: e.target.value }) : b)}
                  data-testid="input-edit-title"
                />
              </div>
              <div>
                <Label>Subtext</Label>
                <Textarea
                  value={editingBanner.subtitle || ""}
                  onChange={e => setEditingBanner(b => b ? ({ ...b, subtitle: e.target.value }) : b)}
                  rows={2}
                  data-testid="textarea-edit-subtitle"
                />
              </div>
              <div>
                <Label>Image</Label>
                {editPendingFile ? (
                  <div className="space-y-2">
                    <div className="relative w-full h-32 rounded-lg overflow-hidden border border-border">
                      <img src={editingBanner.imageUrl || ""} alt="Preview" className="w-full h-full object-cover" />
                      <Button size="icon" variant="destructive" className="absolute top-1 right-1 h-6 w-6" onClick={() => { setEditPendingFile(null); setEditingBanner(b => b ? ({ ...b, imageUrl: null }) : b); }}>
                        <X className="h-3 w-3" />
                      </Button>
                    </div>
                    <p className="text-xs text-muted-foreground">{editPendingFile.name}</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <div className="flex gap-2">
                      <Input
                        value={editingBanner.imageUrl || ""}
                        onChange={e => setEditingBanner(b => b ? ({ ...b, imageUrl: e.target.value }) : b)}
                        placeholder="https://..."
                        data-testid="input-edit-image"
                      />
                      <Button type="button" variant="outline" className="shrink-0 gap-1.5" onClick={() => {
                        const input = document.createElement("input");
                        input.type = "file";
                        input.accept = "image/*";
                        input.onchange = (e) => {
                          const file = (e.target as HTMLInputElement).files?.[0];
                          if (file) handleEditFileSelect(file);
                        };
                        input.click();
                      }} data-testid="button-edit-pick-image">
                        <Upload className="h-4 w-4" />
                        Upload
                      </Button>
                    </div>
                    {(editingBanner.imageUrl && !editPendingFile) && (
                      <div className="w-full h-24 rounded-lg overflow-hidden border border-border">
                        <img src={imageDisplayUrl(editingBanner.id, editingBanner.imageUrl) || editingBanner.imageUrl} alt="Current" className="w-full h-full object-cover" />
                      </div>
                    )}
                  </div>
                )}
              </div>
              <ExpirySection
                value={editingBanner.expiresAt || ""}
                onChange={v => setEditingBanner(b => b ? ({ ...b, expiresAt: v }) : b)}
              />
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => { setEditingBanner(null); setEditPendingFile(null); }}>Cancel</Button>
              <Button
                onClick={() => updateMutation.mutate({
                  id: editingBanner.id,
                  data: {
                    title: editingBanner.title,
                    subtitle: editingBanner.subtitle,
                    imageUrl: editPendingFile ? undefined : editingBanner.imageUrl,
                    expiresAt: editingBanner.expiresAt || null,
                  } as any
                })}
                disabled={!editingBanner.title.trim() || updateMutation.isPending}
                data-testid="button-save-edit"
              >
                {updateMutation.isPending && <Loader2 className="h-4 w-4 animate-spin mr-2" />}
                Save Changes
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  );
}
